---
version: "2.0"

services:
  app:
    image: ghcr.io/arno01/app:v0.0.6
    env:
      - SLEEP=65
      #- SVWAIT=7
      #- VERBOSE=1
      - GH_USER=arno01
      - GH_REPO=self-update
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000

deployment:
  app:
    akash:
      profile: app
      count: 1
