#!/bin/bash

[[ ! -z "$VERBOSE" ]] && set -x

SVC="${PWD##*/}"

if [[ -z "$GH_USER" ]] || [[ -z "$GH_REPO" ]]; then
  echo "[$SVC] Please set GH_USER, GH_REPO environment variables!"
  sv stop $SVC
fi

REL_API_URL="https://api.github.com/repos/${GH_USER}/${GH_REPO}/releases/latest"
SLEEP=${SLEEP:-300}
echo "[$SVC] monitoring the new releases at $REL_API_URL every $SLEEP seconds"

DATA_FILE="/tmp/data"
PID_FILE="/etc/service/app/supervise/pid"
# runit-less pid location:
# /var/run/app.pid

function UpdateApp() {
  wget -qO "$DATA_FILE" "$REL_API_URL"
  if [[ ! -f "$DATA_FILE" ]]; then
    echo "[$SVC] Cannot obtain the latest release information!"
    return 1
  fi

  URL="$(jq -Mr '.assets[] | select(.browser_download_url | test(".*_linux_amd64.tar.gz$")) | .browser_download_url' "$DATA_FILE")"
  VER="$(jq -Mr 'select(.assets[].browser_download_url | test(".*_linux_amd64.tar.gz$")) | .tag_name' "$DATA_FILE")"
  rm -f /tmp/data

  if [[ ! -z "$VERBOSE" ]]; then
    echo "[$SVC] URL: $URL"
    echo "[$SVC] VER: $VER"
  fi

  if [[ -z "$VER" ]]; then
    echo "[$SVC] Cannot determine the latest release version, something went wrong!"
    return 1
  fi

  # /version is passed through build-time variables (--build-arg) during image build.
  CUR_VER="$(cat /version)"

  if [[ -z "$CUR_VER" ]] || [[ "$VER" != "$CUR_VER" ]]; then
    echo "[$SVC] Detected a new release $VER, going to update now."
    wget --show-progress -qO /tmp/update.tar.gz "$URL"
    # TODO: verify checksum + GPG signature before extracting the archive.
    set -x
    sv stop app
    tar -C /usr/local/bin -xovzf /tmp/update.tar.gz -- app
    rm -f /tmp/update.tar.gz
    CUR_VER="$VER"
    echo "$CUR_VER" | tee /version >/dev/null
    sv start app
    set +x
    return 0
  fi
  # TODO: might try updating self-updating script itself.
  # Probably isn't worth doing so as there are more chances it will break things.
  return 1
}

while true; do
  UpdateApp;

  # firstrun marker used by the app service
  [[ ! -e /tmp/update.firstrun ]] && touch /tmp/update.firstrun

  # Github API Rate limits
  # For unauthenticated requests, the rate limit allows for up to 60 requests per hour.
  # So make sure to not set sleep to a lower than 1 minute value.
  sleep $SLEEP
done
