#!/bin/sh

[[ ! -z "$VERBOSE" ]] && set -x

SVC="${PWD##*/}"

sv start update || exit 1

# Wait for the auto-update script to make sure we never run an older version
# should the new one be found.
until [ -e /tmp/update.firstrun ]; do
  sleep 1
done

echo "[$SVC] starting ..."
exec /usr/local/bin/app
