---
name: "release"

# https://goreleaser.com/ci/actions/
# https://github.com/goreleaser/goreleaser-action
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
# https://docs.github.com/en/actions/learn-github-actions/contexts

on:
  push:
    tags:
      - 'v*'

#permissions:
#  contents: write
#  packages: write
#  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PAT_WRITE_PACKAGES }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: ${{ github.repository_owner }}
